/* compiler_rt_msvc_math.h — Resolve math symbol conflicts on Windows MSVC.
 *
 * When compiler_rt.c is generated by the zig C backend (-ofmt=c), it exports
 * standard math functions (fabs, round, ceil, floor, sqrt, etc.) with strong
 * linkage. On Windows with MSVC CRT (static /MT or dynamic /MD), these same
 * symbols are provided by the CRT (ucrt.lib / libucrt.lib), causing duplicate
 * symbol linker errors (or requiring /FORCE:MULTIPLE which causes heap corruption).
 *
 * This header is force-included (/FI) when compiling compiler_rt.c on MSVC.
 * It redefines the standard math function names to prefixed versions (__zig_*)
 * so that compiler_rt's implementations don't collide with the CRT.
 * The CRT's implementations are used instead by zig2.c (which includes <math.h>).
 *
 * The generated compiler_rt.c uses patterns like:
 *   #define compiler_rt_fabs_fabs__2079 fabs
 *   zig_extern zig_f64 fabs(zig_f64 a0);
 *   ...
 *   zig_f64 compiler_rt_fabs_fabs__2079(zig_f64 const a0) { ... }
 *
 * By defining e.g. fabs=__zig_crt_fabs BEFORE the file is processed, the
 * preprocessor rewrites both the #define RHS and the forward declaration,
 * so the compiled object exports __zig_crt_fabs instead of fabs.
 */

#if defined(_WIN32) && (defined(_MSC_VER) || defined(__clang__))

/* Standard double-precision math (conflict with ucrt) */
#define fabs    __zig_crt_fabs
#define fabsf   __zig_crt_fabsf
#define fabsl   __zig_crt_fabsl
#define round   __zig_crt_round
#define roundf  __zig_crt_roundf
#define roundl  __zig_crt_roundl
#define ceil    __zig_crt_ceil
#define ceilf   __zig_crt_ceilf
#define ceill   __zig_crt_ceill
#define floor   __zig_crt_floor
#define floorf  __zig_crt_floorf
#define floorl  __zig_crt_floorl
#define sqrt    __zig_crt_sqrt
#define sqrtf   __zig_crt_sqrtf
#define sqrtl   __zig_crt_sqrtl
#define sin     __zig_crt_sin
#define sinf    __zig_crt_sinf
#define sinl    __zig_crt_sinl
#define cos     __zig_crt_cos
#define cosf    __zig_crt_cosf
#define cosl    __zig_crt_cosl
#define tan     __zig_crt_tan
#define tanf    __zig_crt_tanf
#define tanl    __zig_crt_tanl
#define exp     __zig_crt_exp
#define expf    __zig_crt_expf
#define expl    __zig_crt_expl
#define exp2    __zig_crt_exp2
#define exp2f   __zig_crt_exp2f
#define exp2l   __zig_crt_exp2l
#define log     __zig_crt_log
#define logf    __zig_crt_logf
#define logl    __zig_crt_logl
#define log2    __zig_crt_log2
#define log2f   __zig_crt_log2f
#define log2l   __zig_crt_log2l
#define log10   __zig_crt_log10
#define log10f  __zig_crt_log10f
#define log10l  __zig_crt_log10l
#define fmod    __zig_crt_fmod
#define fmodf   __zig_crt_fmodf
#define fmodl   __zig_crt_fmodl
#define fmin    __zig_crt_fmin
#define fminf   __zig_crt_fminf
#define fminl   __zig_crt_fminl
#define fmax    __zig_crt_fmax
#define fmaxf   __zig_crt_fmaxf
#define fmaxl   __zig_crt_fmaxl
#define fma     __zig_crt_fma
#define fmaf    __zig_crt_fmaf
#define fmal    __zig_crt_fmal
#define trunc   __zig_crt_trunc
#define truncf  __zig_crt_truncf
#define truncl  __zig_crt_truncl

/* sincos is not in MSVC CRT but rename anyway for consistency */
#define sincos  __zig_crt_sincos
#define sincosf __zig_crt_sincosf
#define sincosl __zig_crt_sincosl

/* __powidf2 etc. are not CRT symbols, no conflict — leave them alone */

#endif /* _WIN32 && (_MSC_VER || __clang__) */
